# -*- coding: utf-8 -*-
"""
把 xingce-deploy 下的三个笔记页合并成单文件 HTML。
方案：每个子页整体转成 base64 data URI，塞进 srcdoc-free 的 iframe src 里，
这样 CSS/ID/脚本完全隔离，原页面零改动，且成品是真正的单文件。
"""
import base64
import os
import re
import io

SRC = r"d:\TRAE SOLO CN\workspace\xingce-deploy"
OUT = r"d:\TRAE SOLO CN\workspace\xingce-deploy\all-in-one.html"

PAGES = [
    ("study",  "study-notes.html",        "言语理解", "📖"),
    ("data",   "data-analysis-notes.html","资料分析", "📈"),
    ("error",  "error-notes.html",        "错题集",   "📝"),
]

def read(p):
    with io.open(p, "r", encoding="utf-8") as f:
        return f.read()

def to_data_uri(html):
    b = html.encode("utf-8")
    return "data:text/html;charset=utf-8;base64," + base64.b64encode(b).decode("ascii")

frames = []
tabs = []
meta = []

for key, fname, label, icon in PAGES:
    path = os.path.join(SRC, fname)
    html = read(path)
    # 记录字符数供校验
    meta.append((fname, len(html)))
    uri = to_data_uri(html)
    frames.append(
        '<iframe class="page-frame" id="frame-%s" data-key="%s" src="%s" '
        'title="%s" loading="lazy"></iframe>' % (key, key, uri, label)
    )
    tabs.append(
        '<button class="tab" data-target="%s"><span class="tab-icon">%s</span>'
        '<span class="tab-label">%s</span></button>' % (key, icon, label)
    )

shell = u"""<!-- Generated by Trae Work -->
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>行测笔记合集 · 言语理解 / 资料分析 / 错题集</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  :root {
    --bg:#f8fafc; --ink:#0f172a; --muted:#64748b;
    --accent:#2563eb; --surface:#ffffff; --border:#e2e8f0;
  }
  html, body { height:100%; }
  body {
    font-family:-apple-system,"Microsoft YaHei","PingFang SC",sans-serif;
    background:var(--bg); color:var(--ink);
    display:flex; flex-direction:column;
  }

  /* 顶部条 */
  .topbar {
    background:linear-gradient(135deg,#0f172a 0%,#1e40af 55%,#2563eb 100%);
    color:#fff; padding:0.9rem 1.2rem 0;
    box-shadow:0 2px 12px rgba(15,23,42,0.18);
    flex:0 0 auto;
  }
  .topbar h1 {
    font-size:1.05rem; font-weight:700; letter-spacing:0.02em;
    display:flex; align-items:center; gap:0.45rem; margin-bottom:0.75rem;
  }
  .topbar h1 .hint {
    font-size:0.75rem; font-weight:400; opacity:0.72; margin-left:auto;
  }

  /* 标签栏 */
  .tabs { display:flex; gap:0.35rem; }
  .tab {
    appearance:none; border:0; cursor:pointer;
    background:rgba(255,255,255,0.12); color:rgba(255,255,255,0.82);
    padding:0.6rem 1.1rem; border-radius:10px 10px 0 0;
    font-size:0.92rem; font-weight:600; font-family:inherit;
    display:flex; align-items:center; gap:0.4rem;
    transition:background 0.18s, color 0.18s;
  }
  .tab:hover { background:rgba(255,255,255,0.2); color:#fff; }
  .tab.active { background:var(--bg); color:var(--accent); }

  /* 内容区 */
  .stage { flex:1 1 auto; position:relative; min-height:0; }
  .page-frame {
    position:absolute; inset:0;
    width:100%; height:100%; border:0; display:none;
    background:var(--bg);
  }
  .page-frame.active { display:block; }

  @media (max-width:640px) {
    .topbar { padding:0.7rem 0.6rem 0; }
    .topbar h1 { font-size:0.92rem; }
    .topbar h1 .hint { display:none; }
    .tab { padding:0.5rem 0.7rem; font-size:0.82rem; }
    .tab-icon { display:none; }
  }
</style>
</head>
<body>

<header class="topbar">
  <h1>📊 行测笔记合集<span class="hint">单文件 · 可离线 · 可分享</span></h1>
  <nav class="tabs">
    __TABS__
  </nav>
</header>

<main class="stage">
  __FRAMES__
</main>

<script>
(function () {
  var tabs   = Array.prototype.slice.call(document.querySelectorAll('.tab'));
  var frames = Array.prototype.slice.call(document.querySelectorAll('.page-frame'));

  function activate(key) {
    tabs.forEach(function (t) {
      t.classList.toggle('active', t.getAttribute('data-target') === key);
    });
    frames.forEach(function (f) {
      f.classList.toggle('active', f.getAttribute('data-key') === key);
    });
    try { history.replaceState(null, '', '#' + key); } catch (e) {}
  }

  tabs.forEach(function (t) {
    t.addEventListener('click', function () {
      activate(t.getAttribute('data-target'));
    });
  });

  // 支持 #data 这类深链直达
  var initial = (location.hash || '').replace('#', '');
  var valid = frames.some(function (f) { return f.getAttribute('data-key') === initial; });
  activate(valid ? initial : frames[0].getAttribute('data-key'));
})();
</script>

</body>
</html>
"""

shell = shell.replace("__TABS__", "\n    ".join(tabs))
shell = shell.replace("__FRAMES__", "\n  ".join(frames))

with io.open(OUT, "w", encoding="utf-8") as f:
    f.write(shell)

size = os.path.getsize(OUT)
print("OK ->", OUT)
print("size: %.1f KB" % (size / 1024.0))
for fname, n in meta:
    print("  embedded %-26s %6d chars" % (fname, n))
